namespace: plattformsikkerhet
team: plattformsikkerhet
ingresses:
  - https://dingser.prod-gcp.nais.io
env:
  - name: APPLICATION_PROFILE
    value: PROD
  - name: APPLICATION_REDIRECT_URL
    value: "https://dingser.prod-gcp.nais.io/oauth"
replicas:
  min: 1
  max: 1
outbound-host:
  - oidc.difi.no
  - tokendings.prod-gcp.nais.io
  - dings-validate.prod-gcp.nais.io
