name: Build, push, and deploy to GCP

on:
  push:
    branches:
      - master

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/exchange:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    if: "github.ref == 'refs/heads/master'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup build cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle wrapper cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Run tests
        run: ./gradlew clean test
      - name: Build with Gradle
        run: ./gradlew shadowJar -x test

      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
          docker push ${IMAGE}

  deploy-dev-gcp:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/naiserator.yml
          VARS: .nais/dev-gcp-vars.yml

 #deploy-prod-gcp:
 #  name: Deploy to prod-gcp
 #  needs: deploy-dev-gcp
 #  if: "github.ref == 'refs/heads/master'"
 #  runs-on: ubuntu-latest
 #  steps:
 #    - uses: actions/checkout@v2
 #    - uses: nais/deploy/actions/deploy@v1
 #      env:
 #        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
 #        CLUSTER: prod-gcp
 #        RESOURCE: .nais/naiserator.yml
 #        VARS: .nais/prod-gcp-vars.yml
